// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    list: 'list__list--nmQmc',
    listItem: 'list__list-item--3VK6d',
    listItemLink: 'list__list-item-link--2VfYS',
    visited: 'list__visited--3D4ln',
} as const;

export type ClassName = string;

export default styles;