// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    list: 'list__list--2T118',
    listItem: 'list__list-item--18g0H',
    listItemLink: 'list__list-item-link--24wJ-',
    visited: 'list__visited--1gFll',
} as const;

export type ClassName = string;

export default styles;