// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    list: 'list__list--t7B83',
    listItem: 'list__list-item--1dLox',
    listItemLink: 'list__list-item-link--84UWR',
    visited: 'list__visited--1WL-d',
} as const;

export type ClassName = string;

export default styles;