// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    popup: 'popup__popup--1cPme',
    title: 'popup__title--3pMWf',
} as const;

export type ClassName = string;

export default styles;