// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    content: 'content__content--2-DP5',
} as const;

export type ClassName = string;

export default styles;